name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    env:
      working-directory: images/image_for_web_server/

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ${{ env.working-directory }}
      run: |
        sudo docker build -t coyhub.azurecr.io/web-server .
        sudo docker push coyhub.azurecr.io/web-server
        sudo docker pull eakkaya64/result-server
        sudo docker tag eakkaya64/result-server coyhub.azurecr.io/result-server
        sudo docker push coyhub.azurecr.io/result-server
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'coywebapp-1'
        images: 'coyhub.azurecr.io/web-server'
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'coywebapp-2'
        images: 'coyhub.azurecr.io/result-server'
